# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nokia/NB1/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    bluetooth \
    cda \
    cmnlib \
    cmnlib64 \
    devcfg \
    dsp \
    hidden \
    hyp \
    keymaster \
    mdtp \
    mdtpsecapp \
    modem \
    nvdef \
    pmic \
    rpm \
    splash \
    systeminfo \
    tz \
    xbl
