#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/nokia/NB1

PRODUCT_COPY_FILES += \
    vendor/nokia/NB1/proprietary/vendor/etc/acdbdata/NB1/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/NB1/Bluetooth_cal.acdb \
    vendor/nokia/NB1/proprietary/vendor/etc/acdbdata/NB1/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/NB1/General_cal.acdb \
    vendor/nokia/NB1/proprietary/vendor/etc/acdbdata/NB1/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/NB1/Global_cal.acdb \
    vendor/nokia/NB1/proprietary/vendor/etc/acdbdata/NB1/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/NB1/Handset_cal.acdb \
    vendor/nokia/NB1/proprietary/vendor/etc/acdbdata/NB1/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/NB1/Hdmi_cal.acdb \
    vendor/nokia/NB1/proprietary/vendor/etc/acdbdata/NB1/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/NB1/Headset_cal.acdb \
    vendor/nokia/NB1/proprietary/vendor/etc/acdbdata/NB1/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/NB1/Speaker_cal.acdb \
    vendor/nokia/NB1/proprietary/vendor/etc/acdbdata/NB1/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/NB1/workspaceFile.qwsp \
    vendor/nokia/NB1/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/nokia/NB1/proprietary/vendor/etc/audio/silence_48k.wav:$(TARGET_COPY_OUT_VENDOR)/etc/audio/silence_48k.wav \
    vendor/nokia/NB1/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/nokia/NB1/proprietary/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/nokia/NB1/proprietary/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/nokia/NB1/proprietary/vendor/etc/camera/imx258_color_nb1_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx258_color_nb1_chromatix.xml \
    vendor/nokia/NB1/proprietary/vendor/etc/camera/imx258_mono_nb1_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx258_mono_nb1_chromatix.xml \
    vendor/nokia/NB1/proprietary/vendor/etc/camera/s5k3l8_front_nb1_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3l8_front_nb1_chromatix.xml \
    vendor/nokia/NB1/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/nokia/NB1/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/nokia/NB1/proprietary/vendor/firmware/TP_Firmware_JDI:$(TARGET_COPY_OUT_VENDOR)/firmware/TP_Firmware_JDI \
    vendor/nokia/NB1/proprietary/vendor/firmware/TP_Firmware_LG4946:$(TARGET_COPY_OUT_VENDOR)/firmware/TP_Firmware_LG4946 \
    vendor/nokia/NB1/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/nokia/NB1/proprietary/vendor/firmware/a540_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b00 \
    vendor/nokia/NB1/proprietary/vendor/firmware/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b01 \
    vendor/nokia/NB1/proprietary/vendor/firmware/a540_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b02 \
    vendor/nokia/NB1/proprietary/vendor/firmware/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.elf \
    vendor/nokia/NB1/proprietary/vendor/firmware/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.mdt \
    vendor/nokia/NB1/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b00 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b01 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b02 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b03 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b04 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b05 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b06 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b07 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.mdt \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfplv.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfplv.b00 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfplv.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfplv.b01 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfplv.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfplv.b02 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfplv.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfplv.b03 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfplv.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfplv.b04 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfplv.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfplv.b05 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfplv.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfplv.b06 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfplv.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfplv.b07 \
    vendor/nokia/NB1/proprietary/vendor/firmware/goodixfplv.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfplv.mdt \
    vendor/nokia/NB1/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/nokia/NB1/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/nokia/NB1/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/nokia/NB1/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/nokia/NB1/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/nokia/NB1/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/nokia/NB1/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/nokia/NB1/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/nokia/NB1/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/nokia/NB1/proprietary/vendor/firmware/tfa98xxEVT.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xxEVT.cnt

PRODUCT_PACKAGES += \
    gatekeeper.msm8998 \
    keystore.msm8998 \
    sound_trigger.primary.msm8998 \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libsensor1 \
    libsensor_reg \
    libsns_low_lat_stream_stub \
    sensor_calibrate \
    sensors.rangefinder \
    sensors.ssc \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libactuator_ak7371 \
    libactuator_ak7371_color_fih \
    libactuator_ak7371_mono_fih \
    libactuator_dw9714 \
    libactuator_dw9714_front_fih \
    libactuator_pseudo \
    libactuator_single_ak7371_mono_fih \
    libadiertac \
    libadm \
    libadpcmdec \
    libaoa \
    libarcsoft_beautyshot \
    libarcsoft_beautyshot_video_algorithm \
    libaudcal \
    libaudioalsa \
    libchromatix_csidtg_common \
    libchromatix_csidtg_cpp_preview \
    libchromatix_csidtg_postproc \
    libchromatix_csidtg_preview \
    libchromatix_csidtg_zsl_preview \
    libchromatix_imx258_color_nb1_4k_preview_3a \
    libchromatix_imx258_color_nb1_4k_video_3a \
    libchromatix_imx258_color_nb1_common \
    libchromatix_imx258_color_nb1_cpp_hfr_120 \
    libchromatix_imx258_color_nb1_cpp_hfr_60 \
    libchromatix_imx258_color_nb1_cpp_hfr_90 \
    libchromatix_imx258_color_nb1_cpp_liveshot \
    libchromatix_imx258_color_nb1_cpp_preview \
    libchromatix_imx258_color_nb1_cpp_snapshot \
    libchromatix_imx258_color_nb1_cpp_video \
    libchromatix_imx258_color_nb1_cpp_video_1080p \
    libchromatix_imx258_color_nb1_cpp_video_4k \
    libchromatix_imx258_color_nb1_cpp_video_720p \
    libchromatix_imx258_color_nb1_default_preview_3a \
    libchromatix_imx258_color_nb1_default_video \
    libchromatix_imx258_color_nb1_default_video_3a \
    libchromatix_imx258_color_nb1_hfr_120 \
    libchromatix_imx258_color_nb1_hfr_120_3a \
    libchromatix_imx258_color_nb1_hfr_60 \
    libchromatix_imx258_color_nb1_hfr_60_3a \
    libchromatix_imx258_color_nb1_hfr_90 \
    libchromatix_imx258_color_nb1_hfr_90_3a \
    libchromatix_imx258_color_nb1_liveshot \
    libchromatix_imx258_color_nb1_postproc \
    libchromatix_imx258_color_nb1_preview \
    libchromatix_imx258_color_nb1_snapshot \
    libchromatix_imx258_color_nb1_versions \
    libchromatix_imx258_color_nb1_video_4k \
    libchromatix_imx258_color_nb1_zsl_preview_3a \
    libchromatix_imx258_color_nb1_zsl_video_3a \
    libchromatix_imx258_front_nb1_4k_preview_3a \
    libchromatix_imx258_front_nb1_4k_video_3a \
    libchromatix_imx258_front_nb1_common \
    libchromatix_imx258_front_nb1_cpp_hfr_120 \
    libchromatix_imx258_front_nb1_cpp_hfr_60 \
    libchromatix_imx258_front_nb1_cpp_hfr_90 \
    libchromatix_imx258_front_nb1_cpp_liveshot \
    libchromatix_imx258_front_nb1_cpp_preview \
    libchromatix_imx258_front_nb1_cpp_snapshot \
    libchromatix_imx258_front_nb1_cpp_video \
    libchromatix_imx258_front_nb1_cpp_video_4k \
    libchromatix_imx258_front_nb1_default_preview_3a \
    libchromatix_imx258_front_nb1_default_video \
    libchromatix_imx258_front_nb1_default_video_3a \
    libchromatix_imx258_front_nb1_hfr_120 \
    libchromatix_imx258_front_nb1_hfr_120_3a \
    libchromatix_imx258_front_nb1_hfr_60 \
    libchromatix_imx258_front_nb1_hfr_60_3a \
    libchromatix_imx258_front_nb1_hfr_90 \
    libchromatix_imx258_front_nb1_hfr_90_3a \
    libchromatix_imx258_front_nb1_liveshot \
    libchromatix_imx258_front_nb1_postproc \
    libchromatix_imx258_front_nb1_preview \
    libchromatix_imx258_front_nb1_snapshot \
    libchromatix_imx258_front_nb1_versions \
    libchromatix_imx258_front_nb1_video_4k \
    libchromatix_imx258_front_nb1_zsl_preview_3a \
    libchromatix_imx258_front_nb1_zsl_video_3a \
    libchromatix_imx258_mono_nb1_4k_preview_3a \
    libchromatix_imx258_mono_nb1_4k_video_3a \
    libchromatix_imx258_mono_nb1_common \
    libchromatix_imx258_mono_nb1_cpp_hfr_120 \
    libchromatix_imx258_mono_nb1_cpp_hfr_60 \
    libchromatix_imx258_mono_nb1_cpp_hfr_90 \
    libchromatix_imx258_mono_nb1_cpp_liveshot \
    libchromatix_imx258_mono_nb1_cpp_preview \
    libchromatix_imx258_mono_nb1_cpp_snapshot \
    libchromatix_imx258_mono_nb1_cpp_video \
    libchromatix_imx258_mono_nb1_cpp_video_4k \
    libchromatix_imx258_mono_nb1_default_preview_3a \
    libchromatix_imx258_mono_nb1_default_video \
    libchromatix_imx258_mono_nb1_default_video_3a \
    libchromatix_imx258_mono_nb1_hfr_120 \
    libchromatix_imx258_mono_nb1_hfr_120_3a \
    libchromatix_imx258_mono_nb1_hfr_60 \
    libchromatix_imx258_mono_nb1_hfr_60_3a \
    libchromatix_imx258_mono_nb1_hfr_90 \
    libchromatix_imx258_mono_nb1_hfr_90_3a \
    libchromatix_imx258_mono_nb1_liveshot \
    libchromatix_imx258_mono_nb1_postproc \
    libchromatix_imx258_mono_nb1_preview \
    libchromatix_imx258_mono_nb1_snapshot \
    libchromatix_imx258_mono_nb1_versions \
    libchromatix_imx258_mono_nb1_video_4k \
    libchromatix_imx258_mono_nb1_zsl_preview_3a \
    libchromatix_imx258_mono_nb1_zsl_video_3a \
    libchromatix_imx258_single_mono_nb1_4k_preview_3a \
    libchromatix_imx258_single_mono_nb1_4k_video_3a \
    libchromatix_imx258_single_mono_nb1_common \
    libchromatix_imx258_single_mono_nb1_cpp_hfr_120 \
    libchromatix_imx258_single_mono_nb1_cpp_hfr_60 \
    libchromatix_imx258_single_mono_nb1_cpp_hfr_90 \
    libchromatix_imx258_single_mono_nb1_cpp_liveshot \
    libchromatix_imx258_single_mono_nb1_cpp_preview \
    libchromatix_imx258_single_mono_nb1_cpp_snapshot \
    libchromatix_imx258_single_mono_nb1_cpp_video \
    libchromatix_imx258_single_mono_nb1_cpp_video_4k \
    libchromatix_imx258_single_mono_nb1_default_preview_3a \
    libchromatix_imx258_single_mono_nb1_default_video \
    libchromatix_imx258_single_mono_nb1_default_video_3a \
    libchromatix_imx258_single_mono_nb1_hfr_120 \
    libchromatix_imx258_single_mono_nb1_hfr_120_3a \
    libchromatix_imx258_single_mono_nb1_hfr_60 \
    libchromatix_imx258_single_mono_nb1_hfr_60_3a \
    libchromatix_imx258_single_mono_nb1_hfr_90 \
    libchromatix_imx258_single_mono_nb1_hfr_90_3a \
    libchromatix_imx258_single_mono_nb1_liveshot \
    libchromatix_imx258_single_mono_nb1_postproc \
    libchromatix_imx258_single_mono_nb1_preview \
    libchromatix_imx258_single_mono_nb1_snapshot \
    libchromatix_imx258_single_mono_nb1_versions \
    libchromatix_imx258_single_mono_nb1_video_4k \
    libchromatix_imx258_single_mono_nb1_zsl_preview_3a \
    libchromatix_imx258_single_mono_nb1_zsl_video_3a \
    libchromatix_s5k3l8_front_nb1_4k_preview_3a \
    libchromatix_s5k3l8_front_nb1_4k_video_3a \
    libchromatix_s5k3l8_front_nb1_common \
    libchromatix_s5k3l8_front_nb1_cpp_hfr_120 \
    libchromatix_s5k3l8_front_nb1_cpp_hfr_60 \
    libchromatix_s5k3l8_front_nb1_cpp_hfr_90 \
    libchromatix_s5k3l8_front_nb1_cpp_liveshot \
    libchromatix_s5k3l8_front_nb1_cpp_preview \
    libchromatix_s5k3l8_front_nb1_cpp_preview_hfr_120 \
    libchromatix_s5k3l8_front_nb1_cpp_snapshot \
    libchromatix_s5k3l8_front_nb1_cpp_video \
    libchromatix_s5k3l8_front_nb1_cpp_video_4k \
    libchromatix_s5k3l8_front_nb1_default_preview_3a \
    libchromatix_s5k3l8_front_nb1_default_video \
    libchromatix_s5k3l8_front_nb1_default_video_3a \
    libchromatix_s5k3l8_front_nb1_hfr_120 \
    libchromatix_s5k3l8_front_nb1_hfr_120_3a \
    libchromatix_s5k3l8_front_nb1_hfr_60 \
    libchromatix_s5k3l8_front_nb1_hfr_60_3a \
    libchromatix_s5k3l8_front_nb1_hfr_90 \
    libchromatix_s5k3l8_front_nb1_hfr_90_3a \
    libchromatix_s5k3l8_front_nb1_liveshot \
    libchromatix_s5k3l8_front_nb1_postproc \
    libchromatix_s5k3l8_front_nb1_preview \
    libchromatix_s5k3l8_front_nb1_snapshot \
    libchromatix_s5k3l8_front_nb1_versions \
    libchromatix_s5k3l8_front_nb1_video_4k \
    libchromatix_s5k3l8_front_nb1_zsl_preview_3a \
    libchromatix_s5k3l8_front_nb1_zsl_video_3a \
    libdepthmapwrapper \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_bokeh \
    libmmcamera_cat24c64_MONO_eeprom \
    libmmcamera_cat24c64_RGB_eeprom \
    libmmcamera_csidtg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_imx258_at24c64d_front_fih_eeprom \
    libmmcamera_imx258_color_fih \
    libmmcamera_imx258_front_fih \
    libmmcamera_imx258_mono_fih \
    libmmcamera_irs1645 \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_ohp0497_eeprom \
    libmmcamera_onsemi_cat24c32_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k3l8 \
    libmmcamera_s5k3l8_mono \
    libmmcamera_s5k3l8_nb1 \
    libmmcamera_s5k3m2xm \
    libmmcamera_s5k3m2xx \
    libmmcamera_s5k3m3sm \
    libmmcamera_s5k3p3sm \
    libmmcamera_s5k3p8sp \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libois_bu24218 \
    libois_bu63165 \
    libois_lc898122 \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libsmwrapper \
    fingerprint.msm8998 \
    gxfingerprint.default \
    libfp_client \
    libfpservice \
    libpn548ad_fw \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    libFastRPC_AUE_Forward_skel \
    libFastRPC_UTF_Forward_Qtc2_skel \
    libFastRPC_UTF_Forward_skel \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libscveBlobDescriptor_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libsns_low_lat_stream_skel \
    libvpp_frc \
    libvpp_svc_skel \
    HotwordEnrollmentOKGoogleWCD9335 \
    HotwordEnrollmentTGoogleWCD9335 \
    HotwordEnrollmentXGoogleWCD9335 \
    gx_fpd \
    qdcm_calib_data_JDI_Dual_nt36850_cmd_mode_dsi_panel_without_DSC.xml \
    qdcm_calib_data_LGD_Dual_DSI_cmd_mode_panel_without_DSC.xml \
    sensors.qti
